name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  unit:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: sbt coverage +test coverageReport
        shell: bash
      - uses: codecov/codecov-action@v1
